spring.application.name=PrimeshopAPI

spring.datasource.url=jdbc:mysql://localhost:3306/primeshop_api_db?serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=MsQLrkst611

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=clave-super-secreta-nexus-2026-itson-minimo-32-chars
jwt.expiration=86400000
